<?php
/**
 * CreatedMachineResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Paperspace
 *
 * Swagger representation of the Paperspace HTTP API
 *
 * OpenAPI spec version: 0.1.1
 * Contact: support@paperspace.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CreatedMachineResponseTest Class Doc Comment
 *
 * @category    Class */
// * @description CreatedMachineResponse
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CreatedMachineResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CreatedMachineResponse"
     */
    public function testCreatedMachineResponse()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "os"
     */
    public function testPropertyOs()
    {
    }

    /**
     * Test attribute "ram"
     */
    public function testPropertyRam()
    {
    }

    /**
     * Test attribute "cpus"
     */
    public function testPropertyCpus()
    {
    }

    /**
     * Test attribute "gpu"
     */
    public function testPropertyGpu()
    {
    }

    /**
     * Test attribute "storage_total"
     */
    public function testPropertyStorageTotal()
    {
    }

    /**
     * Test attribute "storage_used"
     */
    public function testPropertyStorageUsed()
    {
    }

    /**
     * Test attribute "usage_rate"
     */
    public function testPropertyUsageRate()
    {
    }

    /**
     * Test attribute "shutdown_timeout_in_hours"
     */
    public function testPropertyShutdownTimeoutInHours()
    {
    }

    /**
     * Test attribute "shutdown_timeout_forces"
     */
    public function testPropertyShutdownTimeoutForces()
    {
    }

    /**
     * Test attribute "perform_auto_snapshot"
     */
    public function testPropertyPerformAutoSnapshot()
    {
    }

    /**
     * Test attribute "auto_snapshot_frequency"
     */
    public function testPropertyAutoSnapshotFrequency()
    {
    }

    /**
     * Test attribute "auto_snapshot_save_count"
     */
    public function testPropertyAutoSnapshotSaveCount()
    {
    }

    /**
     * Test attribute "agent_type"
     */
    public function testPropertyAgentType()
    {
    }

    /**
     * Test attribute "dt_created"
     */
    public function testPropertyDtCreated()
    {
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
    }

    /**
     * Test attribute "network_id"
     */
    public function testPropertyNetworkId()
    {
    }

    /**
     * Test attribute "private_ip_address"
     */
    public function testPropertyPrivateIpAddress()
    {
    }

    /**
     * Test attribute "public_ip_address"
     */
    public function testPropertyPublicIpAddress()
    {
    }

    /**
     * Test attribute "region"
     */
    public function testPropertyRegion()
    {
    }

    /**
     * Test attribute "user_id"
     */
    public function testPropertyUserId()
    {
    }

    /**
     * Test attribute "team_id"
     */
    public function testPropertyTeamId()
    {
    }
}
