<?php
/**
 * MachinesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Gamingsolved\Paperspace\Api\Client\Version0_1_3
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Paperspace REST API
 *
 * Inofficial Swagger representation of the [Paperspace REST API](https://paperspace.github.io/paperspace-node/), provided by the [GamingSolved Paperspace API PHP Client project](https://github.com/gamingsolved/paperspace-api-php-client).
 *
 * OpenAPI spec version: 0.1.3
 * Contact: info@gamingsolved.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Gamingsolved\Paperspace\Api\Client\Version0_1_3;

use \Gamingsolved\Paperspace\Api\Client\Version0_1_3\Configuration;
use \Gamingsolved\Paperspace\Api\Client\Version0_1_3\ApiException;
use \Gamingsolved\Paperspace\Api\Client\Version0_1_3\ObjectSerializer;

/**
 * MachinesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Gamingsolved\Paperspace\Api\Client\Version0_1_3
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MachinesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createMachine
     *
     * Create and launch a new Paperspace virtual machine.
     *
     */
    public function testCreateMachine()
    {
    }

    /**
     * Test case for destroyMachine
     *
     * Destroy a machine.
     *
     */
    public function testDestroyMachine()
    {
    }

    /**
     * Test case for listMachines
     *
     * List information about all machines available.
     *
     */
    public function testListMachines()
    {
    }

    /**
     * Test case for restartMachine
     *
     * Restart an individual machine.
     *
     */
    public function testRestartMachine()
    {
    }

    /**
     * Test case for showMachine
     *
     * Show machine information.
     *
     */
    public function testShowMachine()
    {
    }

    /**
     * Test case for startMachine
     *
     * Start up an individual machine.
     *
     */
    public function testStartMachine()
    {
    }

    /**
     * Test case for stopMachine
     *
     * Stop an individual machine.
     *
     */
    public function testStopMachine()
    {
    }
}
