<?php
/**
 * MachinesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Gamingsolved\Paperspace\Api\Client\Version0_1_1
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Paperspace
 *
 * Swagger representation of the Paperspace HTTP API
 *
 * OpenAPI spec version: 0.1.3
 * Contact: support@paperspace.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Gamingsolved\Paperspace\Api\Client\Version0_1_1;

use \Gamingsolved\Paperspace\Api\Client\Version0_1_1\Configuration;
use \Gamingsolved\Paperspace\Api\Client\Version0_1_1\ApiException;
use \Gamingsolved\Paperspace\Api\Client\Version0_1_1\ObjectSerializer;

/**
 * MachinesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Gamingsolved\Paperspace\Api\Client\Version0_1_1
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MachinesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for machinesCreateSingleMachinePublicPost
     *
     * Create and launch a new Paperspace virtual machine.
     *
     */
    public function testMachinesCreateSingleMachinePublicPost()
    {
    }
}
