<?php
/**
 * Machine
 *
 * PHP version 5
 *
 * @category Class
 * @package  Gamingsolved\Paperspace\Api\Client\Version0_1_3
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Paperspace REST API
 *
 * Inofficial Swagger representation of the [Paperspace REST API](https://paperspace.github.io/paperspace-node/), provided by the [GamingSolved](https://github.com/gamingsolved/paperspace-api-php-client) project.
 *
 * OpenAPI spec version: 0.1.3
 * Contact: support@paperspace.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Gamingsolved\Paperspace\Api\Client\Version0_1_3\Model;

use \ArrayAccess;

/**
 * Machine Class Doc Comment
 *
 * @category    Class
 * @package     Gamingsolved\Paperspace\Api\Client\Version0_1_3
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Machine implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'Machine';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'id' => 'string',
        'name' => 'string',
        'os' => 'string',
        'ram' => 'int',
        'cpus' => 'int',
        'gpu' => 'string',
        'storageTotal' => 'int',
        'storageUsed' => 'int',
        'usageRate' => 'string',
        'shutdownTimeoutInHours' => 'int',
        'shutdownTimeoutForces' => 'bool',
        'performAutoSnapshot' => 'bool',
        'autoSnapshotFrequency' => 'int',
        'autoSnapshotSaveCount' => 'int',
        'agentType' => 'string',
        'dtCreated' => 'string',
        'state' => 'string',
        'networkId' => 'string',
        'privateIpAddress' => 'string',
        'publicIpAddress' => 'string',
        'region' => 'string',
        'userId' => 'string',
        'teamId' => 'string',
        'scriptId' => 'string',
        'dtLastRun' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerFormats = [
        'id' => null,
        'name' => null,
        'os' => null,
        'ram' => 'int32',
        'cpus' => 'int32',
        'gpu' => null,
        'storageTotal' => 'int32',
        'storageUsed' => 'int32',
        'usageRate' => null,
        'shutdownTimeoutInHours' => 'int32',
        'shutdownTimeoutForces' => null,
        'performAutoSnapshot' => null,
        'autoSnapshotFrequency' => 'int32',
        'autoSnapshotSaveCount' => 'int32',
        'agentType' => null,
        'dtCreated' => 'datetime',
        'state' => 'datetime',
        'networkId' => null,
        'privateIpAddress' => null,
        'publicIpAddress' => null,
        'region' => null,
        'userId' => null,
        'teamId' => null,
        'scriptId' => null,
        'dtLastRun' => null
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'name' => 'name',
        'os' => 'os',
        'ram' => 'ram',
        'cpus' => 'cpus',
        'gpu' => 'gpu',
        'storageTotal' => 'storageTotal',
        'storageUsed' => 'storageUsed',
        'usageRate' => 'usageRate',
        'shutdownTimeoutInHours' => 'shutdownTimeoutInHours',
        'shutdownTimeoutForces' => 'shutdownTimeoutForces',
        'performAutoSnapshot' => 'performAutoSnapshot',
        'autoSnapshotFrequency' => 'autoSnapshotFrequency',
        'autoSnapshotSaveCount' => 'autoSnapshotSaveCount',
        'agentType' => 'agentType',
        'dtCreated' => 'dtCreated',
        'state' => 'state',
        'networkId' => 'networkId',
        'privateIpAddress' => 'privateIpAddress',
        'publicIpAddress' => 'publicIpAddress',
        'region' => 'region',
        'userId' => 'userId',
        'teamId' => 'teamId',
        'scriptId' => 'scriptId',
        'dtLastRun' => 'dtLastRun'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'name' => 'setName',
        'os' => 'setOs',
        'ram' => 'setRam',
        'cpus' => 'setCpus',
        'gpu' => 'setGpu',
        'storageTotal' => 'setStorageTotal',
        'storageUsed' => 'setStorageUsed',
        'usageRate' => 'setUsageRate',
        'shutdownTimeoutInHours' => 'setShutdownTimeoutInHours',
        'shutdownTimeoutForces' => 'setShutdownTimeoutForces',
        'performAutoSnapshot' => 'setPerformAutoSnapshot',
        'autoSnapshotFrequency' => 'setAutoSnapshotFrequency',
        'autoSnapshotSaveCount' => 'setAutoSnapshotSaveCount',
        'agentType' => 'setAgentType',
        'dtCreated' => 'setDtCreated',
        'state' => 'setState',
        'networkId' => 'setNetworkId',
        'privateIpAddress' => 'setPrivateIpAddress',
        'publicIpAddress' => 'setPublicIpAddress',
        'region' => 'setRegion',
        'userId' => 'setUserId',
        'teamId' => 'setTeamId',
        'scriptId' => 'setScriptId',
        'dtLastRun' => 'setDtLastRun'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'name' => 'getName',
        'os' => 'getOs',
        'ram' => 'getRam',
        'cpus' => 'getCpus',
        'gpu' => 'getGpu',
        'storageTotal' => 'getStorageTotal',
        'storageUsed' => 'getStorageUsed',
        'usageRate' => 'getUsageRate',
        'shutdownTimeoutInHours' => 'getShutdownTimeoutInHours',
        'shutdownTimeoutForces' => 'getShutdownTimeoutForces',
        'performAutoSnapshot' => 'getPerformAutoSnapshot',
        'autoSnapshotFrequency' => 'getAutoSnapshotFrequency',
        'autoSnapshotSaveCount' => 'getAutoSnapshotSaveCount',
        'agentType' => 'getAgentType',
        'dtCreated' => 'getDtCreated',
        'state' => 'getState',
        'networkId' => 'getNetworkId',
        'privateIpAddress' => 'getPrivateIpAddress',
        'publicIpAddress' => 'getPublicIpAddress',
        'region' => 'getRegion',
        'userId' => 'getUserId',
        'teamId' => 'getTeamId',
        'scriptId' => 'getScriptId',
        'dtLastRun' => 'getDtLastRun'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    const REGION_EAST_COAST__NY2 = 'East Coast (NY2)';
    const REGION_WEST_COAST__CA1 = 'West Coast (CA1)';
    

    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getRegionAllowableValues()
    {
        return [
            self::REGION_EAST_COAST__NY2,
            self::REGION_WEST_COAST__CA1,
        ];
    }
    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['os'] = isset($data['os']) ? $data['os'] : null;
        $this->container['ram'] = isset($data['ram']) ? $data['ram'] : null;
        $this->container['cpus'] = isset($data['cpus']) ? $data['cpus'] : null;
        $this->container['gpu'] = isset($data['gpu']) ? $data['gpu'] : null;
        $this->container['storageTotal'] = isset($data['storageTotal']) ? $data['storageTotal'] : null;
        $this->container['storageUsed'] = isset($data['storageUsed']) ? $data['storageUsed'] : null;
        $this->container['usageRate'] = isset($data['usageRate']) ? $data['usageRate'] : null;
        $this->container['shutdownTimeoutInHours'] = isset($data['shutdownTimeoutInHours']) ? $data['shutdownTimeoutInHours'] : null;
        $this->container['shutdownTimeoutForces'] = isset($data['shutdownTimeoutForces']) ? $data['shutdownTimeoutForces'] : null;
        $this->container['performAutoSnapshot'] = isset($data['performAutoSnapshot']) ? $data['performAutoSnapshot'] : null;
        $this->container['autoSnapshotFrequency'] = isset($data['autoSnapshotFrequency']) ? $data['autoSnapshotFrequency'] : null;
        $this->container['autoSnapshotSaveCount'] = isset($data['autoSnapshotSaveCount']) ? $data['autoSnapshotSaveCount'] : null;
        $this->container['agentType'] = isset($data['agentType']) ? $data['agentType'] : null;
        $this->container['dtCreated'] = isset($data['dtCreated']) ? $data['dtCreated'] : null;
        $this->container['state'] = isset($data['state']) ? $data['state'] : null;
        $this->container['networkId'] = isset($data['networkId']) ? $data['networkId'] : null;
        $this->container['privateIpAddress'] = isset($data['privateIpAddress']) ? $data['privateIpAddress'] : null;
        $this->container['publicIpAddress'] = isset($data['publicIpAddress']) ? $data['publicIpAddress'] : null;
        $this->container['region'] = isset($data['region']) ? $data['region'] : null;
        $this->container['userId'] = isset($data['userId']) ? $data['userId'] : null;
        $this->container['teamId'] = isset($data['teamId']) ? $data['teamId'] : null;
        $this->container['scriptId'] = isset($data['scriptId']) ? $data['scriptId'] : null;
        $this->container['dtLastRun'] = isset($data['dtLastRun']) ? $data['dtLastRun'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        $allowed_values = $this->getRegionAllowableValues();
        if (!in_array($this->container['region'], $allowed_values)) {
            $invalid_properties[] = sprintf(
                "invalid value for 'region', must be one of '%s'",
                implode("', '", $allowed_values)
            );
        }

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        $allowed_values = $this->getRegionAllowableValues();
        if (!in_array($this->container['region'], $allowed_values)) {
            return false;
        }
        return true;
    }


    /**
     * Gets id
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     * @param string $id 
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets name
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     * @param string $name 
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets os
     * @return string
     */
    public function getOs()
    {
        return $this->container['os'];
    }

    /**
     * Sets os
     * @param string $os 
     * @return $this
     */
    public function setOs($os)
    {
        $this->container['os'] = $os;

        return $this;
    }

    /**
     * Gets ram
     * @return int
     */
    public function getRam()
    {
        return $this->container['ram'];
    }

    /**
     * Sets ram
     * @param int $ram 
     * @return $this
     */
    public function setRam($ram)
    {
        $this->container['ram'] = $ram;

        return $this;
    }

    /**
     * Gets cpus
     * @return int
     */
    public function getCpus()
    {
        return $this->container['cpus'];
    }

    /**
     * Sets cpus
     * @param int $cpus 
     * @return $this
     */
    public function setCpus($cpus)
    {
        $this->container['cpus'] = $cpus;

        return $this;
    }

    /**
     * Gets gpu
     * @return string
     */
    public function getGpu()
    {
        return $this->container['gpu'];
    }

    /**
     * Sets gpu
     * @param string $gpu 
     * @return $this
     */
    public function setGpu($gpu)
    {
        $this->container['gpu'] = $gpu;

        return $this;
    }

    /**
     * Gets storageTotal
     * @return int
     */
    public function getStorageTotal()
    {
        return $this->container['storageTotal'];
    }

    /**
     * Sets storageTotal
     * @param int $storageTotal 
     * @return $this
     */
    public function setStorageTotal($storageTotal)
    {
        $this->container['storageTotal'] = $storageTotal;

        return $this;
    }

    /**
     * Gets storageUsed
     * @return int
     */
    public function getStorageUsed()
    {
        return $this->container['storageUsed'];
    }

    /**
     * Sets storageUsed
     * @param int $storageUsed 
     * @return $this
     */
    public function setStorageUsed($storageUsed)
    {
        $this->container['storageUsed'] = $storageUsed;

        return $this;
    }

    /**
     * Gets usageRate
     * @return string
     */
    public function getUsageRate()
    {
        return $this->container['usageRate'];
    }

    /**
     * Sets usageRate
     * @param string $usageRate 
     * @return $this
     */
    public function setUsageRate($usageRate)
    {
        $this->container['usageRate'] = $usageRate;

        return $this;
    }

    /**
     * Gets shutdownTimeoutInHours
     * @return int
     */
    public function getShutdownTimeoutInHours()
    {
        return $this->container['shutdownTimeoutInHours'];
    }

    /**
     * Sets shutdownTimeoutInHours
     * @param int $shutdownTimeoutInHours 
     * @return $this
     */
    public function setShutdownTimeoutInHours($shutdownTimeoutInHours)
    {
        $this->container['shutdownTimeoutInHours'] = $shutdownTimeoutInHours;

        return $this;
    }

    /**
     * Gets shutdownTimeoutForces
     * @return bool
     */
    public function getShutdownTimeoutForces()
    {
        return $this->container['shutdownTimeoutForces'];
    }

    /**
     * Sets shutdownTimeoutForces
     * @param bool $shutdownTimeoutForces 
     * @return $this
     */
    public function setShutdownTimeoutForces($shutdownTimeoutForces)
    {
        $this->container['shutdownTimeoutForces'] = $shutdownTimeoutForces;

        return $this;
    }

    /**
     * Gets performAutoSnapshot
     * @return bool
     */
    public function getPerformAutoSnapshot()
    {
        return $this->container['performAutoSnapshot'];
    }

    /**
     * Sets performAutoSnapshot
     * @param bool $performAutoSnapshot 
     * @return $this
     */
    public function setPerformAutoSnapshot($performAutoSnapshot)
    {
        $this->container['performAutoSnapshot'] = $performAutoSnapshot;

        return $this;
    }

    /**
     * Gets autoSnapshotFrequency
     * @return int
     */
    public function getAutoSnapshotFrequency()
    {
        return $this->container['autoSnapshotFrequency'];
    }

    /**
     * Sets autoSnapshotFrequency
     * @param int $autoSnapshotFrequency 
     * @return $this
     */
    public function setAutoSnapshotFrequency($autoSnapshotFrequency)
    {
        $this->container['autoSnapshotFrequency'] = $autoSnapshotFrequency;

        return $this;
    }

    /**
     * Gets autoSnapshotSaveCount
     * @return int
     */
    public function getAutoSnapshotSaveCount()
    {
        return $this->container['autoSnapshotSaveCount'];
    }

    /**
     * Sets autoSnapshotSaveCount
     * @param int $autoSnapshotSaveCount 
     * @return $this
     */
    public function setAutoSnapshotSaveCount($autoSnapshotSaveCount)
    {
        $this->container['autoSnapshotSaveCount'] = $autoSnapshotSaveCount;

        return $this;
    }

    /**
     * Gets agentType
     * @return string
     */
    public function getAgentType()
    {
        return $this->container['agentType'];
    }

    /**
     * Sets agentType
     * @param string $agentType 
     * @return $this
     */
    public function setAgentType($agentType)
    {
        $this->container['agentType'] = $agentType;

        return $this;
    }

    /**
     * Gets dtCreated
     * @return string
     */
    public function getDtCreated()
    {
        return $this->container['dtCreated'];
    }

    /**
     * Sets dtCreated
     * @param string $dtCreated 
     * @return $this
     */
    public function setDtCreated($dtCreated)
    {
        $this->container['dtCreated'] = $dtCreated;

        return $this;
    }

    /**
     * Gets state
     * @return string
     */
    public function getState()
    {
        return $this->container['state'];
    }

    /**
     * Sets state
     * @param string $state 
     * @return $this
     */
    public function setState($state)
    {
        $this->container['state'] = $state;

        return $this;
    }

    /**
     * Gets networkId
     * @return string
     */
    public function getNetworkId()
    {
        return $this->container['networkId'];
    }

    /**
     * Sets networkId
     * @param string $networkId 
     * @return $this
     */
    public function setNetworkId($networkId)
    {
        $this->container['networkId'] = $networkId;

        return $this;
    }

    /**
     * Gets privateIpAddress
     * @return string
     */
    public function getPrivateIpAddress()
    {
        return $this->container['privateIpAddress'];
    }

    /**
     * Sets privateIpAddress
     * @param string $privateIpAddress 
     * @return $this
     */
    public function setPrivateIpAddress($privateIpAddress)
    {
        $this->container['privateIpAddress'] = $privateIpAddress;

        return $this;
    }

    /**
     * Gets publicIpAddress
     * @return string
     */
    public function getPublicIpAddress()
    {
        return $this->container['publicIpAddress'];
    }

    /**
     * Sets publicIpAddress
     * @param string $publicIpAddress 
     * @return $this
     */
    public function setPublicIpAddress($publicIpAddress)
    {
        $this->container['publicIpAddress'] = $publicIpAddress;

        return $this;
    }

    /**
     * Gets region
     * @return string
     */
    public function getRegion()
    {
        return $this->container['region'];
    }

    /**
     * Sets region
     * @param string $region 
     * @return $this
     */
    public function setRegion($region)
    {
        $allowed_values = $this->getRegionAllowableValues();
        if (!is_null($region) && !in_array($region, $allowed_values)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'region', must be one of '%s'",
                    implode("', '", $allowed_values)
                )
            );
        }
        $this->container['region'] = $region;

        return $this;
    }

    /**
     * Gets userId
     * @return string
     */
    public function getUserId()
    {
        return $this->container['userId'];
    }

    /**
     * Sets userId
     * @param string $userId 
     * @return $this
     */
    public function setUserId($userId)
    {
        $this->container['userId'] = $userId;

        return $this;
    }

    /**
     * Gets teamId
     * @return string
     */
    public function getTeamId()
    {
        return $this->container['teamId'];
    }

    /**
     * Sets teamId
     * @param string $teamId 
     * @return $this
     */
    public function setTeamId($teamId)
    {
        $this->container['teamId'] = $teamId;

        return $this;
    }

    /**
     * Gets scriptId
     * @return string
     */
    public function getScriptId()
    {
        return $this->container['scriptId'];
    }

    /**
     * Sets scriptId
     * @param string $scriptId 
     * @return $this
     */
    public function setScriptId($scriptId)
    {
        $this->container['scriptId'] = $scriptId;

        return $this;
    }

    /**
     * Gets dtLastRun
     * @return string
     */
    public function getDtLastRun()
    {
        return $this->container['dtLastRun'];
    }

    /**
     * Sets dtLastRun
     * @param string $dtLastRun 
     * @return $this
     */
    public function setDtLastRun($dtLastRun)
    {
        $this->container['dtLastRun'] = $dtLastRun;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Gamingsolved\Paperspace\Api\Client\Version0_1_3\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Gamingsolved\Paperspace\Api\Client\Version0_1_3\ObjectSerializer::sanitizeForSerialization($this));
    }
}


