<?php
/**
 * ListMachinesParamsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Gamingsolved\Paperspace\Api\Client\Version0_1_3
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Paperspace REST API
 *
 * Inofficial Swagger representation of the [Paperspace REST API](https://paperspace.github.io/paperspace-node/), provided by the [GamingSolved](https://github.com/gamingsolved/paperspace-api-php-client) project.
 *
 * OpenAPI spec version: 0.1.3
 * Contact: support@paperspace.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Gamingsolved\Paperspace\Api\Client\Version0_1_3;

/**
 * ListMachinesParamsTest Class Doc Comment
 *
 * @category    Class */
// * @description ListMachinesParams
/**
 * @package     Gamingsolved\Paperspace\Api\Client\Version0_1_3
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ListMachinesParamsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ListMachinesParams"
     */
    public function testListMachinesParams()
    {
    }

    /**
     * Test attribute "machineId"
     */
    public function testPropertyMachineId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "os"
     */
    public function testPropertyOs()
    {
    }

    /**
     * Test attribute "ram"
     */
    public function testPropertyRam()
    {
    }

    /**
     * Test attribute "cpus"
     */
    public function testPropertyCpus()
    {
    }

    /**
     * Test attribute "gpu"
     */
    public function testPropertyGpu()
    {
    }

    /**
     * Test attribute "storageTotal"
     */
    public function testPropertyStorageTotal()
    {
    }

    /**
     * Test attribute "storageUsed"
     */
    public function testPropertyStorageUsed()
    {
    }

    /**
     * Test attribute "usageRate"
     */
    public function testPropertyUsageRate()
    {
    }

    /**
     * Test attribute "shutdownTimeoutInHours"
     */
    public function testPropertyShutdownTimeoutInHours()
    {
    }

    /**
     * Test attribute "performAutoSnapshot"
     */
    public function testPropertyPerformAutoSnapshot()
    {
    }

    /**
     * Test attribute "autoSnapshotFrequency"
     */
    public function testPropertyAutoSnapshotFrequency()
    {
    }

    /**
     * Test attribute "autoSnapshotSaveCount"
     */
    public function testPropertyAutoSnapshotSaveCount()
    {
    }

    /**
     * Test attribute "agentType"
     */
    public function testPropertyAgentType()
    {
    }

    /**
     * Test attribute "dtCreated"
     */
    public function testPropertyDtCreated()
    {
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
    }

    /**
     * Test attribute "networkId"
     */
    public function testPropertyNetworkId()
    {
    }

    /**
     * Test attribute "privateIpAddress"
     */
    public function testPropertyPrivateIpAddress()
    {
    }

    /**
     * Test attribute "publicIpAddress"
     */
    public function testPropertyPublicIpAddress()
    {
    }

    /**
     * Test attribute "region"
     */
    public function testPropertyRegion()
    {
    }

    /**
     * Test attribute "userId"
     */
    public function testPropertyUserId()
    {
    }

    /**
     * Test attribute "teamId"
     */
    public function testPropertyTeamId()
    {
    }

    /**
     * Test attribute "scriptId"
     */
    public function testPropertyScriptId()
    {
    }

    /**
     * Test attribute "dtLastRun"
     */
    public function testPropertyDtLastRun()
    {
    }
}
