<?php
/**
 * MachineCreationParamsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Gamingsolved\Paperspace\Api\Client\Version0_1_3
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Paperspace
 *
 * Swagger representation of the Paperspace HTTP API
 *
 * OpenAPI spec version: 0.1.3
 * Contact: support@paperspace.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Gamingsolved\Paperspace\Api\Client\Version0_1_3;

/**
 * MachineCreationParamsTest Class Doc Comment
 *
 * @category    Class */
// * @description MachineCreationParams
/**
 * @package     Gamingsolved\Paperspace\Api\Client\Version0_1_3
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MachineCreationParamsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "MachineCreationParams"
     */
    public function testMachineCreationParams()
    {
    }

    /**
     * Test attribute "region"
     */
    public function testPropertyRegion()
    {
    }

    /**
     * Test attribute "machineType"
     */
    public function testPropertyMachineType()
    {
    }

    /**
     * Test attribute "size"
     */
    public function testPropertySize()
    {
    }

    /**
     * Test attribute "billingType"
     */
    public function testPropertyBillingType()
    {
    }

    /**
     * Test attribute "machineName"
     */
    public function testPropertyMachineName()
    {
    }

    /**
     * Test attribute "templateId"
     */
    public function testPropertyTemplateId()
    {
    }

    /**
     * Test attribute "assignPublicIp"
     */
    public function testPropertyAssignPublicIp()
    {
    }

    /**
     * Test attribute "networkId"
     */
    public function testPropertyNetworkId()
    {
    }

    /**
     * Test attribute "teamId"
     */
    public function testPropertyTeamId()
    {
    }

    /**
     * Test attribute "userId"
     */
    public function testPropertyUserId()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "password"
     */
    public function testPropertyPassword()
    {
    }

    /**
     * Test attribute "firstName"
     */
    public function testPropertyFirstName()
    {
    }

    /**
     * Test attribute "lastName"
     */
    public function testPropertyLastName()
    {
    }

    /**
     * Test attribute "notificationEmail"
     */
    public function testPropertyNotificationEmail()
    {
    }

    /**
     * Test attribute "scriptId"
     */
    public function testPropertyScriptId()
    {
    }
}
